name: Playwright Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs:
      TEST_EXEC_EXECUTION_KEY:
        description: 'Execution Key'
        required: false
        default: ''
      TEST_EXEC_INPUT_TYPE:
        description: 'Input Type'
        required: true
        default: 'Key'
        type: choice
        options:
          - Key
          - Label
      TEST_EXEC_INPUT_VALUE:
        description: 'Input Value'
        required: true
        default: ''

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      SECRETS_JSON: ${{ toJSON(secrets) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # =========================
      # Build playwright-custom-core
      # =========================
      - name: Install core dependencies
        working-directory: playwright-custom-core
        run: npm install

      - name: Build core package
        working-directory: playwright-custom-core
        run: npm run build

      - name: Create npm package
        working-directory: playwright-custom-core
        run: npm pack

      - name: Get package name
        id: pkg
        working-directory: playwright-custom-core
        run: |
          FILE=$(ls *.tgz)
          echo "FILE=$FILE" >> $GITHUB_ENV

      - name: Upload core package artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-core-package
          path: playwright-custom-core/${{ env.FILE }}

      # =========================
      # Setup salesforce-automation-example
      # =========================
      - name: Install automation dependencies
        working-directory: salesforce-automation-example
        run: npm install

      - name: Write Salesforce private key to file
        working-directory: salesforce-automation-example
        run: printf "%b" "${{ secrets.SF_PRIVATE_KEY_PATH }}" > server.key
      # =========================
      # Create .env from secrets
      # =========================

      - name: Create .env file from template and inputs
        working-directory: salesforce-automation-example
        run: |
          echo "$SECRETS_JSON" > secrets.json
          rm -f .env
          while IFS='=' read -r var _; do
            clean_var=$(echo "$var" | sed 's/\$//g' | xargs)
            value=$(jq -r --arg v "$clean_var" '.[$v] // empty' secrets.json)
            [ -n "$value" ] && echo "$clean_var=$value" >> .env
          done < .env.template
          echo "TEST_EXEC_INPUT_TYPE=$TEST_EXEC_INPUT_TYPE" >> .env
          echo "TEST_EXEC_INPUT_VALUE=$TEST_EXEC_INPUT_VALUE" >> .env
          echo "SF_PRIVATE_KEY_PATH=server.key" >> .env
        env:
          SECRETS_JSON: ${{ toJSON(secrets) }}
          TEST_EXEC_INPUT_TYPE: ${{ github.event.inputs.TEST_EXEC_INPUT_TYPE || github.event.client_payload.TEST_EXEC_INPUT_TYPE }}
          TEST_EXEC_INPUT_VALUE: ${{ github.event.inputs.TEST_EXEC_INPUT_VALUE || github.event.client_payload.TEST_EXEC_INPUT_VALUE }}


      # =========================
      # Run Playwright Test
      # =========================
      - name: Install Playwright Browsers
        working-directory: salesforce-automation-example
        run: npx playwright install --with-deps

      - name: Run Playwright Test
        working-directory: salesforce-automation-example
        run: |
          npx ts-node Run.ts
